### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by BijuuKrunos** [Minebench/Pipes#7]
Hello, it would be fantastic if you could add multi-language Support, based on client, for this Plugin. Thanks :)

**Comment by BijuuKrunos** [comment]
<3 thanks

**Comment by Phoenix616** [comment]
Added now for every place where this is easily possible (GUI, chat messages). Unfortunately this isn't easily doable server-side for item names/lores and requires a resource pack so they will use the default locale as a fallback for now but I look into supporting resource packs too.
